spring:
  profiles:
    active: local
  kafka:
    bootstrap-servers: broker:29092
    topic:
      avro: transactions
    properties:
      schema.registry.url: http://schema-registry:8081
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      client-id: app0
      group-id: payment-debug-consumer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      auto-offset-reset: earliest
      properties:
        group.protocol: consumer
        specific.avro.reader: true
  docker:
    compose:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
  docker:
    compose:
      enabled: true
      lifecycle-management: start-only
      file: ../example-streams-app/compose.yml
