spring:
  profiles:
    active: local
  kafka:
    bootstrap-servers: broker:29092
    topic:
      avro: payment-demo
    properties:
      schema.registry.url: http://schema-registry:8081
    producer:
      key-serializer:
        class: org.apache.kafka.common.serialization.StringSerializer
      value-serializer:
        class: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      auto-offset-reset: earliest
  docker:
    compose:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
  docker:
    compose:
      enabled: true
      lifecycle-management: start-only
      file: ../example-streams-app/compose.yml
